# Generated by Django 5.2.5 on 2025-09-19 04:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("short_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "대학",
                "verbose_name_plural": "대학",
                "db_table": "college",
            },
        ),
        migrations.CreateModel(
            name="MemberRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("is_leadership", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_player", models.BooleanField(default=False)),
                ("is_manager", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "역할",
                "verbose_name_plural": "역할",
                "db_table": "member_role",
            },
        ),
        migrations.CreateModel(
            name="MemberStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "부원 활동 상태",
                "verbose_name_plural": "부원 활동 상태",
                "db_table": "member_status",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("short_name", models.CharField(max_length=50, unique=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.college",
                    ),
                ),
            ],
            options={
                "verbose_name": "학과",
                "verbose_name_plural": "학과",
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=15, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "admission_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("date_joined", models.DateField(blank=True, null=True)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "major",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="members.department",
                    ),
                ),
                (
                    "profile_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="assets.snubaseballimage",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="members.memberrole",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="members.memberstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "부원",
                "verbose_name_plural": "부원",
                "db_table": "member",
                "ordering": ["admission_year"],
            },
        ),
    ]
