# Generated by Django 5.2.5 on 2025-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="student_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
