# Generated by Django 4.2.17 on 2024-12-23 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('num_views', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('is_drill', models.BooleanField(default=False)),
                ('is_indoor', models.BooleanField(default=False)),
                ('min_people', models.IntegerField(default=0)),
                ('max_people', models.IntegerField(default=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guideline',
            },
        ),
        migrations.CreateModel(
            name='GuidelineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'guideline_category',
            },
        ),
        migrations.CreateModel(
            name='GuidelineLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='guideline.guideline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guideline_like',
            },
        ),
        migrations.CreateModel(
            name='GuidelineContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_first_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_last_at', models.DateTimeField(auto_now=True)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guideline.guideline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guideline_content_view',
            },
        ),
        migrations.CreateModel(
            name='GuidelineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='guideline.guideline')),
            ],
            options={
                'db_table': 'guideline_comment',
            },
        ),
        migrations.AddField(
            model_name='guideline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guideline.guidelinecategory'),
        ),
    ]
