# Generated by Django 4.2.17 on 2025-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideline',
            options={'verbose_name': '가이드라인', 'verbose_name_plural': '가이드라인'},
        ),
        migrations.AlterModelOptions(
            name='guidelinecategory',
            options={'verbose_name': '가이드라인 분류', 'verbose_name_plural': '가이드라인 분류'},
        ),
        migrations.AlterModelOptions(
            name='guidelinecomment',
            options={'verbose_name': '가이드라인 댓글', 'verbose_name_plural': '가이드라인 댓글'},
        ),
        migrations.AlterModelOptions(
            name='guidelinecontentview',
            options={'verbose_name': '가이드라인 조회', 'verbose_name_plural': '가이드라인 조회'},
        ),
        migrations.AlterModelOptions(
            name='guidelinelike',
            options={'verbose_name': '가이드라인 좋아요', 'verbose_name_plural': '가이드라인 좋아요'},
        ),
    ]
