# Generated by Django 4.2.17 on 2025-03-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0002_alter_guideline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideline',
            name='is_youtube',
            field=models.BooleanField(default=True),
        ),
    ]
