# Generated by Django 4.2.17 on 2025-03-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideline', '0003_guideline_is_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideline',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='guideline/thumbnails/'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
