# Generated by Django 5.2.5 on 2025-09-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SNUBaseballAsset",
            fields=[
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="asset",
                        serialize=False,
                        to="storage.storedfile",
                    ),
                ),
            ],
            options={
                "db_table": "assets",
                "ordering": ["-file__created_at"],
            },
        ),
        migrations.CreateModel(
            name="SNUBaseballImage",
            fields=[
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="image",
                        serialize=False,
                        to="storage.storedfile",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "images",
                "ordering": ["-file__created_at"],
            },
        ),
        migrations.CreateModel(
            name="SNUBaseballVideo",
            fields=[
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="video",
                        serialize=False,
                        to="storage.storedfile",
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "videos",
                "ordering": ["-file__created_at"],
            },
        ),
    ]
