# Generated by Django 5.2.5 on 2025-09-19 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SNUBaseballAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=512, unique=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SNUBaseballImage",
            fields=[
                (
                    "snubaseballasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.snubaseballasset",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "images",
            },
            bases=("assets.snubaseballasset",),
        ),
        migrations.CreateModel(
            name="SNUBaseballVideo",
            fields=[
                (
                    "snubaseballasset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.snubaseballasset",
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "videos",
            },
            bases=("assets.snubaseballasset",),
        ),
    ]
