# Generated by Django 5.2.5 on 2025-09-26 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="snubaseballasset",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="snubaseballimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="snubaseballvideo",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="snubaseballasset",
            index=models.Index(
                fields=["uploaded_by"], name="assets_uploade_836ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snubaseballimage",
            index=models.Index(
                fields=["uploaded_by"], name="images_uploade_6bd8cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snubaseballvideo",
            index=models.Index(
                fields=["uploaded_by"], name="videos_uploade_78ee76_idx"
            ),
        ),
    ]
