# Generated by Django 5.2.6 on 2025-09-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snubaseballvideo",
            name="thumbnail_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
