# Generated by Django 5.2.5 on 2025-08-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "부원 활동 상태",
                "verbose_name_plural": "부원 활동 상태",
                "db_table": "member_status",
            },
        ),
    ]
