import {
  createDiscussion,
  updateDiscussion,
  deleteDiscussion,
  likeDiscussion,
  getDiscussions,
  getDiscussionDetails,
  createDiscussionComment,
  editDiscussionComment,
  deleteDiscussionComment,
} from "./discussions";
import {
  createNotice,
  getNotices,
  getNoticeDetails,
  getNoticeCategories,
  updateNotice,
  deleteNotice,
  likeNotice,
  createNoticeComment,
  editNoticeComment,
  deleteNoticeComment,
} from "./notices";

export {
  createDiscussion,
  updateDiscussion,
  deleteDiscussion,
  likeDiscussion,
  getDiscussions,
  getDiscussionDetails,
  createDiscussionComment,
  editDiscussionComment,
  deleteDiscussionComment,
  createNotice,
  getNotices,
  getNoticeDetails,
  getNoticeCategories,
  updateNotice,
  deleteNotice,
  likeNotice,
  createNoticeComment,
  editNoticeComment,
  deleteNoticeComment,
};
