sonar.projectKey=vietman2_SNUBaseball2
sonar.organization=vietman2
sonar.projectName=SNUBaseball
sonar.projectVersion=1.0
sonar.sources=baseballserver,baseballteam,snubaseball
sonar.python.version=3.13
sonar.exclusions=\
**/migrations/*,\
**/__init__.py,\
**/wsgi.py,\
**/asgi.py,\
**/manage.py
sonar.coverage.exclusions=\
**/@x/*,\
**/*.test.tsx,\
**/*.test.ts,\
**/context.ts,\
**/index.ts,\
**/routes.tsx,\
**/styles.ts,\
**/*.types.ts,\
**/types.ts,\
**/setup.tsx,\
**/*.d.ts,\
**/*.config.js,\
**/__init__.py,\
**/manage.py,\
**/config/*,
**/migrations/*,\
**/tests/*,\
**/admin.py,\
**/api.py,\
**/urls.py,\
**/fixtures/*,\
sonar.javascript.lcov.reportPaths=baseballteam/coverage.lcov,snubaseball/coverage.lcov
sonar.python.coverage.reportPaths=baseballserver/coverage.xml