# Generated by Django 5.2.5 on 2025-08-29 06:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("major", "0001_initial"),
        ("member_status", "0001_initial"),
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=15, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "admission_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("extras", models.JSONField(blank=True, default=dict)),
                ("date_joined", models.DateField(blank=True, null=True)),
                (
                    "num_semester",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="major.department",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="role.memberrole",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="member_status.memberstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "부원",
                "verbose_name_plural": "부원",
                "db_table": "member",
                "ordering": ["admission_year"],
            },
        ),
    ]
