# Generated by Django 5.2.5 on 2025-09-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="back_number",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
