# Generated by Django 4.2.15 on 2024-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_college_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
