# Generated by Django 4.2.15 on 2024-08-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_person_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
