# Generated by Django 4.2.15 on 2024-08-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_person_address_alter_person_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
