# Generated by Django 4.2.17 on 2025-03-16 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0003_alter_member_address_alter_member_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('members_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='BaseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, '이미지'), (2, '비디오')], default=1)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='gallery.album')),
                ('people', models.ManyToManyField(blank=True, related_name='media', to='member.member')),
            ],
            options={
                'db_table': 'base_media',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archive/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='archive/videos/thumbnails/')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='gallery.basemedia')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='archive/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='archive/images/thumbnails/')),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='gallery.basemedia')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='basemedia',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media', to='gallery.tag'),
        ),
        migrations.AddField(
            model_name='basemedia',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
    ]
