# Generated by Django 4.2.17 on 2025-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='basemedia',
            name='title',
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
