# Generated by Django 4.2.17 on 2025-02-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_album_cover_photo_remove_basemedia_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemedia',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
