# Generated by Django 4.2.17 on 2025-02-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_basemedia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='archive/images/thumbnails/'),
        ),
    ]
