# Generated by Django 4.2.17 on 2025-03-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='archive/videos/thumbnails/'),
        ),
    ]
