# Generated by Django 4.2.17 on 2025-03-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_album_members_only_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
    ]
