# Generated by Django 4.2.17 on 2025-03-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_album_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='exif_data',
        ),
    ]
