# Generated by Django 4.2.17 on 2025-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelOptions(
            name='discussionattachment',
            options={'verbose_name': '게시글 첨부파일', 'verbose_name_plural': '게시글 첨부파일'},
        ),
        migrations.AlterModelOptions(
            name='discussioncomment',
            options={'verbose_name': '게시글 댓글', 'verbose_name_plural': '게시글 댓글'},
        ),
        migrations.AlterModelOptions(
            name='discussioncontentview',
            options={'verbose_name': '게시글 조회', 'verbose_name_plural': '게시글 조회'},
        ),
        migrations.AlterModelOptions(
            name='discussionlike',
            options={'verbose_name': '게시글 좋아요', 'verbose_name_plural': '게시글 좋아요'},
        ),
    ]
