# Generated by Django 4.2.17 on 2025-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name': '공지', 'verbose_name_plural': '공지'},
        ),
        migrations.AlterModelOptions(
            name='noticeattachment',
            options={'verbose_name': '공지 첨부파일', 'verbose_name_plural': '공지 첨부파일'},
        ),
        migrations.AlterModelOptions(
            name='noticecategory',
            options={'verbose_name': '공지 분류', 'verbose_name_plural': '공지 분류'},
        ),
        migrations.AlterModelOptions(
            name='noticecomment',
            options={'verbose_name': '공지 댓글', 'verbose_name_plural': '공지 댓글'},
        ),
        migrations.AlterModelOptions(
            name='noticecontentview',
            options={'verbose_name': '공지 조회', 'verbose_name_plural': '공지 조회'},
        ),
        migrations.AlterModelOptions(
            name='noticelike',
            options={'verbose_name': '공지 좋아요', 'verbose_name_plural': '공지 좋아요'},
        ),
    ]
