# Generated by Django 4.2.15 on 2024-10-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='num_clicks',
            new_name='num_views',
        ),
    ]
