# Generated by Django 4.2.15 on 2024-10-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_notice_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeLike',
        ),
    ]
