# Generated by Django 5.2.3 on 2025-06-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("short_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "대학",
                "verbose_name_plural": "대학",
                "db_table": "college",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("short_name", models.CharField(max_length=50, unique=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="major.college"
                    ),
                ),
            ],
            options={
                "verbose_name": "학과",
                "verbose_name_plural": "학과",
                "db_table": "department",
            },
        ),
    ]
