# Generated by Django 4.2.17 on 2025-01-11 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccount', '0001_initial'),
        ('member', '0003_alter_member_address_alter_member_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, '수입'), (2, '지출')], default=2)),
                ('category', models.IntegerField(choices=[(1, '식비'), (2, '교통비'), (3, '숙박비'), (4, '훈련용품비'), (9, '기타')], default=9)),
                ('method', models.IntegerField(choices=[(1, '카드'), (2, '계좌이체'), (9, '기타')], default=9)),
                ('counter_party', models.CharField(max_length=20)),
                ('balance_after', models.IntegerField()),
                ('notes', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccount.account')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
