# Generated by Django 4.2.17 on 2025-01-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': '거래', 'verbose_name_plural': '거래'},
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
