# Generated by Django 4.2.17 on 2025-01-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id'], 'verbose_name': '거래', 'verbose_name_plural': '거래'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.IntegerField(choices=[(0, '수입'), (1, '식비'), (2, '교통비'), (3, '숙박비'), (4, '훈련용품비'), (9, '기타')], default=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.IntegerField(choices=[(0, '수입'), (1, '카드'), (2, '계좌이체'), (9, '기타')], default=9),
        ),
    ]
