# Generated by Django 4.2.17 on 2025-01-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_options_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.IntegerField(choices=[(0, '수입'), (1, '식비'), (2, '교통비'), (3, '숙박비'), (4, '야구용품비'), (5, '선수등록비'), (9, '기타')], default=9),
        ),
    ]
