# Generated by Django 4.2.15 on 2024-10-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackcontentview_feedbackcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcomment',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback'),
        ),
    ]
