# Generated by Django 5.2.5 on 2025-09-26 06:11

import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=512,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "스토리지 파일",
                "verbose_name_plural": "스토리지 파일",
                "db_table": "storage_files",
                "ordering": ["-id"],
            },
        ),
    ]
