# Generated by Django 4.2.15 on 2024-10-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='person',
            new_name='member',
        ),
    ]
