# Generated by Django 5.2.3 on 2025-07-01 07:49

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("major", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("is_leadership", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "역할",
                "verbose_name_plural": "역할",
                "db_table": "member_role",
            },
        ),
        migrations.CreateModel(
            name="MemberStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "부원 활동 상태",
                "verbose_name_plural": "부원 활동 상태",
                "db_table": "member_status",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "admission_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("date_joined", models.DateField(blank=True, null=True)),
                (
                    "num_semester",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                (
                    "hands",
                    models.IntegerField(
                        choices=[
                            (0, ""),
                            (1, "우투우타"),
                            (2, "우투좌타"),
                            (3, "좌투우타"),
                            (4, "좌투좌타"),
                            (5, "양투우타"),
                            (6, "양투좌타"),
                            (7, "우투양타"),
                            (8, "좌투양타"),
                            (9, "양투양타"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "back_number",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                ("is_elite", models.BooleanField(default=False)),
                (
                    "major",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="major.department",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="member.memberrole",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="member.memberstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "부원",
                "verbose_name_plural": "부원",
                "db_table": "member",
                "ordering": ["admission_year"],
            },
        ),
    ]
