# Generated by Django 4.2.17 on 2025-01-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tournament_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='officialgame.tournamentevent'),
        ),
    ]
