# Generated by Django 4.2.17 on 2025-01-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0002_alter_game_tournament_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
