# Generated by Django 4.2.17 on 2025-01-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('officialgame', '0003_game_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('back_number', models.IntegerField(default=0)),
                ('reason', models.TextField(default='')),
                ('goal', models.TextField(default='')),
                ('rival', models.CharField(default='', max_length=20)),
                ('role_model', models.TextField(default='', max_length=20)),
                ('strength', models.TextField(default='', max_length=50)),
                ('weakness', models.TextField(default='', max_length=50)),
                ('is_registered', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialgame.myteam')),
            ],
            options={
                'db_table': 'my_player',
            },
        ),
        migrations.CreateModel(
            name='MyGamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_order', models.IntegerField(choices=[(0, '-'), (1, '1번'), (2, '2번'), (3, '3번'), (4, '4번'), (5, '5번'), (6, '6번'), (7, '7번'), (8, '8번'), (9, '9번'), (10, '선발')], default=0)),
                ('position', models.IntegerField(choices=[(0, '-'), (1, 'P'), (2, 'C'), (3, '1B'), (4, '2B'), (5, '3B'), (6, 'SS'), (7, 'LF'), (8, 'CF'), (9, 'RF'), (10, 'DH')], default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='officialgame.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='officialgame.myplayer')),
            ],
            options={
                'db_table': 'game_player',
            },
        ),
    ]
