# Generated by Django 4.2.17 on 2025-01-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0004_myplayer_mygameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='youtube_videoid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
