# Generated by Django 4.2.17 on 2025-01-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('officialgame', '0005_game_youtube_videoid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': '경기', 'verbose_name_plural': '경기'},
        ),
        migrations.AlterModelOptions(
            name='mygameplayer',
            options={'verbose_name': '선수 (경기)', 'verbose_name_plural': '선수 (경기)'},
        ),
        migrations.AlterModelOptions(
            name='myplayer',
            options={'verbose_name': '등록선수', 'verbose_name_plural': '등록선수'},
        ),
        migrations.AlterModelOptions(
            name='myteam',
            options={'verbose_name': '서울대 (팀)', 'verbose_name_plural': '서울대 (팀)'},
        ),
        migrations.AlterModelOptions(
            name='opponent',
            options={'verbose_name': '상대팀', 'verbose_name_plural': '상대팀'},
        ),
        migrations.AlterUniqueTogether(
            name='myplayer',
            unique_together={('member', 'team')},
        ),
    ]
