# Generated by Django 4.2.17 on 2025-01-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0006_alter_game_options_alter_mygameplayer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myplayer',
            options={'verbose_name': '팀원', 'verbose_name_plural': '팀원'},
        ),
        migrations.RemoveField(
            model_name='mygameplayer',
            name='batting_order',
        ),
        migrations.AlterField(
            model_name='mygameplayer',
            name='position',
            field=models.IntegerField(choices=[(0, '-'), (1, 'P'), (2, 'C'), (3, '1B'), (4, '2B'), (5, '3B'), (6, 'SS'), (7, 'LF'), (8, 'CF'), (9, 'RF'), (10, 'DH'), (11, 'M')], default=0),
        ),
        migrations.CreateModel(
            name='GameLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench', models.ManyToManyField(related_name='bench', to='officialgame.mygameplayer')),
                ('eight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eight', to='officialgame.mygameplayer')),
                ('five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='five', to='officialgame.mygameplayer')),
                ('four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='four', to='officialgame.mygameplayer')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_lineups', to='officialgame.game')),
                ('managers', models.ManyToManyField(related_name='managers', to='officialgame.mygameplayer')),
                ('nine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nine', to='officialgame.mygameplayer')),
                ('one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='officialgame.mygameplayer')),
                ('seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seven', to='officialgame.mygameplayer')),
                ('six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='six', to='officialgame.mygameplayer')),
                ('starting_pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_pitcher', to='officialgame.mygameplayer')),
                ('three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='officialgame.mygameplayer')),
                ('two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='officialgame.mygameplayer')),
            ],
            options={
                'verbose_name': '라인업',
                'verbose_name_plural': '라인업',
                'db_table': 'game_lineup',
            },
        ),
    ]
