# Generated by Django 4.2.17 on 2025-01-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0007_alter_myplayer_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mygameplayer',
            unique_together={('game', 'player')},
        ),
    ]
