# Generated by Django 4.2.17 on 2025-01-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0008_alter_mygameplayer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygameplayer',
            name='position',
            field=models.IntegerField(choices=[(0, '-'), (1, 'P'), (2, 'C'), (3, '1B'), (4, '2B'), (5, '3B'), (6, 'SS'), (7, 'LF'), (8, 'CF'), (9, 'RF'), (10, 'DH'), (11, 'M'), (12, 'B')], default=0),
        ),
    ]
