# Generated by Django 4.2.17 on 2025-01-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0009_alter_mygameplayer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplayer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
