# Generated by Django 4.2.17 on 2025-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0010_myplayer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplayer',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
