# Generated by Django 4.2.17 on 2025-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0011_myplayer_is_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myteam',
            options={'ordering': ['-year'], 'verbose_name': '서울대 (팀)', 'verbose_name_plural': '서울대 (팀)'},
        ),
        migrations.AlterField(
            model_name='myteam',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
