# Generated by Django 4.2.17 on 2025-01-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0012_alter_myteam_options_alter_myteam_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myteam',
            options={'ordering': ['year'], 'verbose_name': '서울대 (팀)', 'verbose_name_plural': '서울대 (팀)'},
        ),
    ]
