# Generated by Django 4.2.17 on 2025-01-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0014_alter_myteam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myplayer',
            name='is_head_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myplayer',
            name='is_vice_captain',
            field=models.BooleanField(default=False),
        ),
    ]
