# Generated by Django 4.2.17 on 2025-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0015_myplayer_is_captain_myplayer_is_head_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ballpark',
            options={'verbose_name': '야구장', 'verbose_name_plural': '야구장'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': '대회명', 'verbose_name_plural': '대회명'},
        ),
        migrations.AlterModelOptions(
            name='tournamentevent',
            options={'verbose_name': '대회', 'verbose_name_plural': '대회'},
        ),
    ]
