# Generated by Django 4.2.17 on 2025-01-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0016_alter_ballpark_options_alter_tournament_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteam',
            name='captain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myteam',
            name='head_coach',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myteam',
            name='head_manager',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myteam',
            name='professor',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myteam',
            name='vice_captain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
