# Generated by Django 4.2.17 on 2025-01-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0017_myteam_captain_myteam_head_coach_myteam_head_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='officialgame.myteam'),
        ),
    ]
