# Generated by Django 4.2.17 on 2025-01-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officialgame', '0018_alter_myplayer_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officialgame.myteam'),
        ),
    ]
