# Generated by Django 5.2.5 on 2025-09-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("members_only", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "앨범",
                "verbose_name_plural": "앨범",
                "db_table": "albums",
            },
        ),
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "미디어 태그",
                "verbose_name_plural": "미디어 태그",
                "db_table": "media_tags",
            },
        ),
        migrations.CreateModel(
            name="GalleryVideo",
            fields=[
                (
                    "snubaseballvideo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.snubaseballvideo",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="gallery.album",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="videos", to="gallery.mediatag"
                    ),
                ),
            ],
            options={
                "verbose_name": "갤러리 비디오",
                "verbose_name_plural": "갤러리 비디오",
                "db_table": "gallery_videos",
            },
            bases=("assets.snubaseballvideo",),
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "snubaseballimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.snubaseballimage",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="gallery.album",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="images", to="gallery.mediatag"
                    ),
                ),
            ],
            options={
                "verbose_name": "갤러리 이미지",
                "verbose_name_plural": "갤러리 이미지",
                "db_table": "gallery_images",
            },
            bases=("assets.snubaseballimage",),
        ),
    ]
