# Generated by Django 5.2.5 on 2025-09-26 06:11

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("members_only", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "앨범",
                "verbose_name_plural": "앨범",
                "db_table": "albums",
            },
        ),
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "미디어 태그",
                "verbose_name_plural": "미디어 태그",
                "db_table": "media_tags",
            },
        ),
        migrations.CreateModel(
            name="GalleryVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="gallery.album",
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_videos",
                        to="assets.snubaseballvideo",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="videos", to="gallery.mediatag"
                    ),
                ),
            ],
            options={
                "verbose_name": "갤러리 비디오",
                "verbose_name_plural": "갤러리 비디오",
                "db_table": "gallery_videos",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="gallery.album",
                    ),
                ),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="assets.snubaseballimage",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="images", to="gallery.mediatag"
                    ),
                ),
            ],
            options={
                "verbose_name": "갤러리 이미지",
                "verbose_name_plural": "갤러리 이미지",
                "db_table": "gallery_images",
            },
        ),
    ]
