# Generated by Django 5.2.6 on 2025-09-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
