# Generated by Django 5.2.6 on 2025-10-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_album_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="mediatag",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
        migrations.AddField(
            model_name="mediatag",
            name="icon",
            field=models.CharField(default="hashtag", max_length=30),
        ),
    ]
