# Generated by Django 5.2.6 on 2025-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_album_color_mediatag_color_mediatag_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="galleryvideo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="galleryvideo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
