# Generated by Django 4.2.17 on 2024-12-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('management_tips', models.TextField(default='')),
                ('person_in_charge', models.ManyToManyField(related_name='equipment_categories', to='member.member')),
            ],
            options={
                'db_table': 'equipment_category',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=100)),
                ('notes', models.CharField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_update_history', to='equipment.equipmentcategory')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'equipment_update_history',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(default='개', max_length=20)),
                ('location', models.IntegerField(choices=[(1, '아카데미'), (2, '창고'), (3, '부실'), (4, '기타')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_set', to='equipment.equipmentcategory')),
            ],
            options={
                'db_table': 'equipment',
                'unique_together': {('location', 'name')},
            },
        ),
    ]
