# Generated by Django 4.2.17 on 2025-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '장비', 'verbose_name_plural': '장비'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name': '장비 분류', 'verbose_name_plural': '장비 분류'},
        ),
        migrations.AlterModelOptions(
            name='equipmentupdatehistory',
            options={'ordering': ['-updated_at'], 'verbose_name': '장비 업데이트 기록', 'verbose_name_plural': '장비 업데이트 기록'},
        ),
    ]
