# Generated by Django 4.2.17 on 2024-12-18 19:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('reason', models.TextField(default='')),
                ('goal', models.TextField(default='')),
                ('rival', models.CharField(default='', max_length=20)),
                ('role_model', models.TextField(default='', max_length=20)),
                ('strength', models.TextField(default='', max_length=50)),
                ('weakness', models.TextField(default='', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tales', to='member.member')),
            ],
            options={
                'db_table': 'tale',
                'unique_together': {('member', 'year')},
            },
        ),
    ]
