# Generated by Django 4.2.15 on 2024-10-15 04:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admission_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('role', models.IntegerField(choices=[(0, '미분류'), (1, '선수'), (2, '매니저'), (3, '지도자'), (9, '기타')], default=0)),
                ('status', models.IntegerField(choices=[(0, '미분류'), (1, '활동'), (2, '비활동'), (3, '졸업'), (9, '기타')], default=0)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='major.department')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
