# Generated by Django 4.2.17 on 2024-12-18 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admission_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('role', models.IntegerField(choices=[(0, '미분류'), (1, '주장'), (2, '부주장'), (3, '수석매니저'), (4, '매니저'), (5, '선수'), (6, '지도자'), (9, '기타')], default=0)),
                ('status', models.IntegerField(choices=[(0, '미분류'), (1, '활동'), (2, '비활동'), (3, '군입대'), (4, '졸업'), (9, '기타')], default=0)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('num_semester', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('position', models.CharField(default='', max_length=10)),
                ('hands', models.IntegerField(choices=[(0, ''), (1, '우투우타'), (2, '우투좌타'), (3, '좌투우타'), (4, '좌투좌타'), (5, '양투우타'), (6, '양투좌타'), (7, '우투양타'), (8, '좌투양타'), (9, '양투양타')], default=0)),
                ('back_number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('is_elite', models.BooleanField(default=False)),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='major.department')),
            ],
            options={
                'db_table': 'member',
                'ordering': ['admission_year'],
            },
        ),
    ]
