# Generated by Django 4.2.17 on 2025-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['admission_year'], 'verbose_name': '부원', 'verbose_name_plural': '부원'},
        ),
    ]
