# Generated by Django 4.2.15 on 2024-10-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_hands_member_position_member_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(0, '미분류'), (1, '선수'), (2, '매니저'), (3, '지도자'), (4, '주장'), (5, '부주장'), (9, '기타')], default=0),
        ),
    ]
