# Generated by Django 4.2.15 on 2024-10-20 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_num_semester_alter_member_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='back_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
