# Generated by Django 4.2.15 on 2024-10-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_back_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hands',
            field=models.IntegerField(choices=[(0, ''), (1, '우투우타'), (2, '우투좌타'), (3, '좌투우타'), (4, '좌투좌타'), (5, '양투우타'), (6, '양투좌타'), (7, '우투양타'), (8, '좌투양타'), (9, '양투양타')], default=0),
        ),
    ]
