# Generated by Django 4.2.15 on 2024-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_member_hands'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_elite',
            field=models.BooleanField(default=False),
        ),
    ]
