# Generated by Django 4.2.17 on 2025-01-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '피드백', 'verbose_name_plural': '피드백'},
        ),
        migrations.AlterModelOptions(
            name='feedbackcategory',
            options={'verbose_name': '피드백 분류', 'verbose_name_plural': '피드백 분류'},
        ),
        migrations.AlterModelOptions(
            name='feedbackcomment',
            options={'verbose_name': '피드백 댓글', 'verbose_name_plural': '피드백 댓글'},
        ),
        migrations.AlterModelOptions(
            name='feedbackcontentview',
            options={'verbose_name': '피드백 조회', 'verbose_name_plural': '피드백 조회'},
        ),
    ]
