# Generated by Django 5.2.5 on 2025-09-22 08:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_alter_member_student_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("semester", models.IntegerField(choices=[(1, "1학기"), (2, "2학기")])),
            ],
            options={
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
                "db_table": "teams",
                "ordering": ["-year", "semester"],
                "unique_together": {("year", "semester")},
            },
        ),
        migrations.CreateModel(
            name="RosterMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MANAGER", "매니저"),
                            ("PLAYER", "선수"),
                            ("PROFESSOR", "지도교수"),
                            ("COACH", "코치"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_captain", models.BooleanField(default=False)),
                ("is_vice_captain", models.BooleanField(default=False)),
                ("is_head_manager", models.BooleanField(default=False)),
                ("is_head_coach", models.BooleanField(default=False)),
                ("position", models.CharField(blank=True, default="", max_length=10)),
                (
                    "hands",
                    models.IntegerField(
                        choices=[
                            (0, "-"),
                            (1, "우투우타"),
                            (2, "우투좌타"),
                            (3, "우투양타"),
                            (4, "좌투좌타"),
                            (5, "좌투우타"),
                            (6, "좌투양타"),
                            (7, "양투양타"),
                            (8, "양투우타"),
                            (9, "양투좌타"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "back_number",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                ("goal", models.CharField(blank=True, default="", max_length=100)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_members",
                        to="members.member",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_members",
                        to="teams.teamroster",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀 멤버",
                "verbose_name_plural": "팀 멤버",
                "db_table": "team_members",
                "unique_together": {("team", "member")},
            },
        ),
    ]
