# Generated by Django 4.2.15 on 2024-10-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='information',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
