# Generated by Django 4.2.17 on 2025-01-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=7)),
                ('background_color', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=20)),
                ('cached_balance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '계좌',
                'verbose_name_plural': '계좌',
                'db_table': 'account',
            },
        ),
    ]
