# Generated by Django 4.2.17 on 2025-01-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, '지원금'), (2, '후원금'), (9, '기타')], default=9),
        ),
    ]
