# Generated by Django 4.2.17 on 2025-01-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
