export type BattingStatsType = {
  name: string;
  num_games: number;
  plate_appearances: number;
  at_bats: number;
  runs: number;
  hits: number;
  doubles: number;
  triples: number;
  home_runs: number;
  total_bases: number;
  runs_batted_in: number;
  stolen_bases: number;
  stolen_bases_caught: number;
  walks: number;
  hit_by_pitch: number;
  strikeouts: number;
  double_plays: number;
  sacrifice_bunts: number;
  sacrifice_flies: number;
  batting_average: number;
  on_base_percentage: number;
  slugging_percentage: number;
  ops: number;
};

export type PitchingStatsType = {
  name: string;
  num_games: number;
  wins: number;
  losses: number;
  innings_pitched: number;
  pitches_thrown: number;
  batters_faced: number;
  at_bats: number;
  hits_allowed: number;
  homeruns_allowed: number;
  walks_allowed: number;
  hit_by_pitch: number;
  strikeouts: number;
  wild_pitches: number;
  balks: number;
  runs_allowed: number;
  earned_runs: number;
  earned_run_average: number;
  whip: number;
  walks_per_nine: number;
  strikeouts_per_nine: number;
  hits_per_nine: number;
  homeruns_per_nine: number;
  strikeout_to_walk: number;
};
