name: Coverall

on:
  pull_request:
    branches:
      - dev

permissions:
  contents: read
        
jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      lcov-path: ${{ steps.install-lcov.outputs.lcov-path }}
    steps:
      - name: Install lcov
        id: install-lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

  server-test:
    runs-on: ubuntu-latest
    needs: prep
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    strategy:
      matrix:
        python-version: [3.13.3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - name: Install dependencies
        run: |
          pip install pipenv
          cd baseballserver
          pipenv install --dev
      
      - name: Run tests and collect coverage
        run: |
          cd baseballserver
          pipenv run coverage run manage.py test
          pipenv run coverage lcov
          pipenv run coverage xml
          sed -i "s|<source></source>|<source>baseballserver</source>|g" coverage.xml

      - name: Upload Server coverage lcov artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage-lcov
          path: baseballserver/coverage.lcov

      - name: Upload Server coverage xml artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage-xml
          path: baseballserver/coverage.xml

  node-tests:
    runs-on: ubuntu-latest
    needs: prep
    strategy:
      matrix:
        project-dir: [baseballteam]
        node-version: [22]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ${{ matrix.project-dir }}/yarn.lock

      - name: Install dependencies
        run: |
          cd ${{ matrix.project-dir }}
          yarn install --dev

      - name: Run tests and collect coverage
        run: |
          cd ${{ matrix.project-dir }}
          yarn coverage
          cp coverage/lcov.info coverage.lcov

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project-dir }}-coverage
          path: ${{ matrix.project-dir }}/coverage.lcov

  quality:
    runs-on: ubuntu-latest
    needs: [server-test, node-tests]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node for merging
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download server lcov artifact
        uses: actions/download-artifact@v4
        with:
          name: server-coverage-lcov
          path: ./baseballserver

      - name: Download server xml artifact
        uses: actions/download-artifact@v4
        with:
          name: server-coverage-xml
          path: ./baseballserver

      - name: Download team page coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: baseballteam-coverage
          path: ./baseballteam

      - name: Merge coverage reports
        run: |
          npx lcov-result-merger '*/coverage.lcov' coverage.lcov \
          --prepend-source-files --prepend-path-fix "."
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
