name: ESLint (team page)

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: 
      - dev
    paths:
      - 'baseballteam/**'

permissions:
  contents: read

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "baseballteam"
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'baseballteam/yarn.lock'

      - name: Install dependencies
        run: |
          yarn install --dev

      - name: Run ESLint
        run: yarn lint
          --config eslint.config.js
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: baseballteam/eslint-results.sarif
          wait-for-processing: true
