name: SNUBaseball CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths:
      - 'baseballserver/**'
      - 'baseballteam/**'
      - 'snubaseball/**'
  push:
    branches:
      - dev
    paths:
      - 'baseballserver/**'
      - 'baseballteam/**'
      - 'snubaseball/**'

permissions:
  contents: read
  security-events: write

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      lcov-path: ${{ steps.install-lcov.outputs.lcov-path }}
    steps:
      - name: Install lcov
        id: install-lcov
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
  
  vite-tests-and-lint:
    runs-on: ubuntu-latest
    needs: prep
    defaults:
      run:
        working-directory: baseballteam
    env:
      VITE_API_URL: "test"
      VITE_ACCESS_TOKEN_KEY: "test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: "baseballteam/yarn.lock"

      - name: Install dependencies
        run: yarn install --dev

      - name: Run tests and collect coverage
        run: |
          yarn coverage
          cp coverage/lcov.info coverage.lcov

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-vite
          path: baseballteam/coverage.lcov

      - name: Run linter
        run: yarn lint --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif

      - name: Upload linter results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: baseballteam/eslint-results.sarif
          wait-for-processing: true

  django-tests-and-lint:
    runs-on: ubuntu-latest
    needs: prep
    defaults:
      run:
        working-directory: baseballserver
    env:
      SECRET_KEY: "test"
      TAILSCALE_IP: "test"
      MEDIA_CDN_BASE_URL: "test"
      AWS_S3_BUCKET_NAME: "test"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      CELERY_BROKER_URL: "test"
      CELERY_RESULT_BACKEND: "test"
      CELERY_WORKER_CONCURRENCY: "2"
      CELERY_WORKER_PREFETCH_MULTIPLIER: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run tests and collect coverage
        run: |
          pipenv run pytest .
          pipenv run coverage lcov

      - name: Upload coverage artifact (lcov)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-django
          path: baseballserver/coverage.lcov

      - name: Run linters
        run: pipenv run sh -c 'DJANGO_SETTINGS_MODULE=config.settings.tests pylint --rcfile=.pylintrc .'

  nextjs-tests-and-lint:
    runs-on: ubuntu-latest
    needs: prep
    defaults:
      run:
        working-directory: snubaseball

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: "snubaseball/yarn.lock"

      - name: Install dependencies
        run: yarn install --dev

      - name: Run tests and collect coverage
        run: |
          yarn test --coverage --watchAll=false
          cp coverage/lcov.info coverage.lcov

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-nextjs
          path: snubaseball/coverage.lcov

      - name: Run linter
        run: yarn lint --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif

      - name: Upload linter results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snubaseball/eslint-results.sarif
          wait-for-processing: true

  quality:
    runs-on: ubuntu-latest
    needs: [django-tests-and-lint, vite-tests-and-lint, nextjs-tests-and-lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node.js 22 (for merging coverage)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download coverage artifact (Vite)
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-vite
          path: ./baseballteam

      - name: Download coverage artifact (Django)
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-django
          path: ./baseballserver

      - name: Download coverage artifact (Next.js)
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-nextjs
          path: ./snubaseball

      - name: Merge coverage reports
        run: |
          npx lcov-result-merger "*/coverage.lcov" coverage.lcov \
          --prepend-source-files --prepend-path-fix "."

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
